import os
import random
import joblib
import numpy as np
import xgboost as xgb
from typing import Dict, List, Set, Tuple, Any, Optional
from .pair_features import extract_pair_features, FEATURE_NAMES

# Try to detect GPU availability for XGBoost
def _detect_gpu() -> bool:
    """Check if CUDA GPU is available for XGBoost."""
    try:
        import cupy
        cupy.cuda.Device(0).compute_capability
        return True
    except Exception:
        pass
    try:
        dtmp = xgb.DMatrix(np.zeros((2, 2), dtype=np.float32), label=[0, 1])
        bst = xgb.train({"device": "cuda", "verbosity": 0, "num_boost_round": 1},
                         dtmp, num_boost_round=1)
        return True
    except Exception:
        return False

GPU_AVAILABLE = _detect_gpu()
print(f"[train] XGBoost GPU available: {GPU_AVAILABLE}")


def construct_training_dataset(
    s1_records: Dict[str, Dict[str, Any]],
    target_records: Dict[str, Dict[str, Any]],
    candidates: Dict[str, Set[str]],
    ground_truth: Dict[str, Set[str]],
    negative_ratio: float = 3.0,
    random_seed: int = 42
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Constructs training feature matrix X and label array y.
    Positives: True matches from ground truth.
    Hard Negatives: Candidates generated by blocking that are not true matches.
    """
    random.seed(random_seed)
    np.random.seed(random_seed)

    X_list = []
    y_list = []

    pos_count = 0
    neg_count = 0

    print("  Extracting training pair features and mining hard negatives...")
    
    for s1_id, s1_rec in s1_records.items():
        true_m = ground_truth.get(s1_id, set())
        cand_m = candidates.get(s1_id, set())

        # 1. Add true matches (positives)
        for mid in true_m:
            target_rec = target_records.get(mid)
            if target_rec:
                feats = extract_pair_features(s1_rec, target_rec, is_s2=mid.startswith("S2-"))
                X_list.append(feats)
                y_list.append(1)
                pos_count += 1

        # 2. Mine hard negatives from candidates
        hard_negs = [c for c in cand_m if c not in true_m and c in target_records]
        # Sample hard negatives according to negative_ratio
        max_negs = max(1, int(len(true_m) * negative_ratio))
        if len(hard_negs) > max_negs:
            hard_negs = random.sample(hard_negs, max_negs)

        for mid in hard_negs:
            target_rec = target_records.get(mid)
            if target_rec:
                feats = extract_pair_features(s1_rec, target_rec, is_s2=mid.startswith("S2-"))
                X_list.append(feats)
                y_list.append(0)
                neg_count += 1

    X = np.array(X_list, dtype=np.float32)
    y = np.array(y_list, dtype=np.int32)
    print(f"  Dataset built: {X.shape[0]:,} pairs ({pos_count:,} positives, {neg_count:,} negatives, ratio: 1:{neg_count/max(1, pos_count):.2f})")
    return X, y


def train_xgboost_gpu_model(
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_val: Optional[np.ndarray] = None,
    y_val: Optional[np.ndarray] = None,
    params: Optional[Dict[str, Any]] = None,
    model_save_path: str = "cache/xgb_model.ubj",
    num_boost_round: int = 500
) -> xgb.Booster:
    """Trains an XGBoost classifier with GPU acceleration (device='cuda')."""
    
    use_gpu = GPU_AVAILABLE
    device = "cuda" if use_gpu else "cpu"
    tree_method = "hist"  # hist works on both CPU and GPU with XGBoost 2.0+
    
    if params is None:
        params = {
            "device": device,
            "tree_method": tree_method,
            "objective": "binary:logistic",
            "eval_metric": "logloss",
            "eta": 0.05,
            "max_depth": 8,
            "min_child_weight": 30,
            "subsample": 0.8,
            "colsample_bytree": 0.8,
            "gamma": 0.1,
            "lambda": 1.0,
            "alpha": 0.1,
            "max_bin": 256,
            "seed": 42,
            "nthread": -1 if not use_gpu else 4,
            "verbosity": 1,
        }
    else:
        params["device"] = device
        params["tree_method"] = tree_method

    print(f"\n--- Training XGBoost Model on {device.upper()} with {len(FEATURE_NAMES)} features ---")
    print(f"  Training samples: {X_train.shape[0]:,}, Features: {X_train.shape[1]}")
    
    dtrain = xgb.DMatrix(X_train, label=y_train, feature_names=FEATURE_NAMES)
    
    evals = [(dtrain, "train")]
    if X_val is not None and y_val is not None:
        dval = xgb.DMatrix(X_val, label=y_val, feature_names=FEATURE_NAMES)
        evals.append((dval, "val"))
        print(f"  Validation samples: {X_val.shape[0]:,}")

    # Train with early stopping
    bst = xgb.train(
        params,
        dtrain,
        num_boost_round=num_boost_round,
        evals=evals,
        early_stopping_rounds=30,
        verbose_eval=50
    )

    # Feature importance
    importance = bst.get_score(importance_type="gain")
    feat_imp = sorted(importance.items(), key=lambda x: x[1], reverse=True)
    print(f"\n  Best iteration: {bst.best_iteration}")
    print("  Top 10 most informative features (gain):")
    for f_name, imp in feat_imp[:10]:
        print(f"    {f_name:25s}: {imp:.2f}")

    os.makedirs(os.path.dirname(model_save_path), exist_ok=True)
    bst.save_model(model_save_path)
    # Also save as joblib for sklearn-compatible wrapper
    joblib.dump(bst, model_save_path.replace(".ubj", ".joblib"))
    print(f"  Model saved to {model_save_path}")
    return bst


# Backward-compatible wrapper that matches old API
def train_lightgbm_model(
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_val: Optional[np.ndarray] = None,
    y_val: Optional[np.ndarray] = None,
    params: Optional[Dict[str, Any]] = None,
    model_save_path: str = "cache/lgb_model.joblib"
) -> Any:
    """
    Backward-compatible entry point. Now delegates to XGBoost GPU.
    Returns a wrapper object with predict_proba() for compatibility.
    """
    xgb_path = model_save_path.replace("lgb_model", "xgb_model").replace(".joblib", ".ubj")
    bst = train_xgboost_gpu_model(
        X_train, y_train, X_val, y_val,
        params=None,
        model_save_path=xgb_path,
        num_boost_round=500
    )
    
    # Return wrapper with predict_proba compatibility
    wrapper = XGBWrapper(bst)
    joblib.dump(wrapper, model_save_path)
    print(f"  Compatible wrapper saved to {model_save_path}")
    return wrapper


class XGBWrapper:
    """Wraps XGBoost Booster with sklearn-compatible predict_proba interface."""
    
    def __init__(self, booster: xgb.Booster):
        self.booster = booster
    
    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """Returns Nx2 array of [1-p, p] probabilities for compatibility."""
        dmat = xgb.DMatrix(X, feature_names=FEATURE_NAMES)
        probs = self.booster.predict(dmat, iteration_range=(0, self.booster.best_iteration + 1))
        return np.column_stack([1 - probs, probs])
    
    def predict(self, X: np.ndarray) -> np.ndarray:
        """Returns probability of positive class."""
        dmat = xgb.DMatrix(X, feature_names=FEATURE_NAMES)
        return self.booster.predict(dmat, iteration_range=(0, self.booster.best_iteration + 1))
